# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/chrome_extension_generator',
                'doc_host': 'https://radekosmulski.github.io',
                'git_url': 'https://github.com/radekosmulski/chrome_extension_generator',
                'lib_path': 'chrome_extension_generator'},
  'syms': { 'chrome_extension_generator.core': { 'chrome_extension_generator.core.create_content_js': ( 'core.html#create_content_js',
                                                                                                        'chrome_extension_generator/core.py'),
                                                 'chrome_extension_generator.core.create_manifest': ( 'core.html#create_manifest',
                                                                                                      'chrome_extension_generator/core.py'),
                                                 'chrome_extension_generator.core.create_readme': ( 'core.html#create_readme',
                                                                                                    'chrome_extension_generator/core.py'),
                                                 'chrome_extension_generator.core.main': ( 'core.html#main',
                                                                                           'chrome_extension_generator/core.py')}}}
