# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/chrome_extension_generator',
                'doc_host': 'https://radekosmulski.github.io',
                'git_url': 'https://github.com/radekosmulski/chrome_extension_generator',
                'lib_path': 'chrome_extension_generator'},
  'syms': { 'chrome_extension_generator.core': { 'chrome_extension_generator.core.foo': ( 'core.html#foo',
                                                                                          'chrome_extension_generator/core.py')}}}
